LISTINGS = [
    {
        "id": 1,
        "title": "2-bed terrace in Wakefield City Centre",
        "price": 184950,
        "area": "City Centre",
        "beds": 2,
        "baths": 1,
        "type": "House",
        "commute": 11,
        "size": 760,
        "url": "#",
    },
    {
        "id": 2,
        "title": "3-bed semi in Outwood",
        "price": 239500,
        "area": "Outwood",
        "beds": 3,
        "baths": 2,
        "type": "Semi-detached",
        "commute": 18,
        "size": 1010,
        "url": "#",
    },
    {
        "id": 3,
        "title": "1-bed flat near Wakefield Westgate",
        "price": 122000,
        "area": "City Centre",
        "beds": 1,
        "baths": 1,
        "type": "Flat",
        "commute": 7,
        "size": 480,
        "url": "#",
    },
    {
        "id": 4,
        "title": "4-bed detached in Sandal",
        "price": 359950,
        "area": "Sandal",
        "beds": 4,
        "baths": 2,
        "type": "Detached",
        "commute": 16,
        "size": 1480,
        "url": "#",
    },
    {
        "id": 5,
        "title": "2-bed semi in Horbury",
        "price": 198000,
        "area": "Horbury",
        "beds": 2,
        "baths": 1,
        "type": "Semi-detached",
        "commute": 20,
        "size": 820,
        "url": "#",
    },
]